### ISSUE TITLE
support for ojs 3.3

### ISSUE THREAD

**Issue by felixhelix** [asmecher/credit#2]
For anyone interested: I created a branch to support ojs 3.3 https://github.com/felixhelix/credit/tree/ops_3-3
Yours
Felix

**Comment by asmecher** [comment]
Thanks, @felixhelix, you beat me to it! I think all the recent changes to the upstream asmecher/credit repo are accounted for here -- except for [this one](https://github.com/asmecher/credit/commit/585c2ecbee8f39e57d891a94bcf599322ce7fb41), which adds better support for translations. Would you mind incorporating that? Then I'll create a `stable-3_3_0` branch and bring your work into it.

**Comment by felixhelix** [comment]
Cool :) Updated the code to work with the new translation repo, also made it work for ojs and ops.

**Comment by asmecher** [comment]
@felixhelix, double-checking the status of the repo, it looks like I already created a [`stable-3_3_0` branch here](https://github.com/asmecher/credit/tree/stable-3_3_0) and ported the plugin back to 3.3.0-x -- did you create your 3.3.0-x back-port independently of that branch?

**Comment by felixhelix** [comment]
Oh yes, indeed I created my back-port independendently :/ 
Thanks Alec for pointing this out!
